# Extraction de caractéristiques à partir du texte
<a href="madani.a@ucd.ac.ma">madani.a@ucd.ac.ma</a>

## Introduction
<p>
Cet article sert d'une simple introduction à l'extraction des caractéristiques à partir de texte en utilisant Sci-Kit Learn de Python. Ces caractéristiques seront utilisées par la suite dans un modèle d'apprentissage automatique.
</p>
<p>
La plupart des algorithmes de machine learning ne peuvent pas traiter directement un texte, nous allons donc créer une matrice de valeurs numériques pour représenter notre texte.
</p>
<p>
Avant d’entrer dans le vif du sujet, il y a quelques termes que nous devons définir dès le départ.
</p>
<ul>
<li><strong>document</strong> : fait référence à une seule information textuelle. Cela pourrait être un message textuel, un tweet, un e-mail, un livre, les paroles d'une chanson. 
<li><strong>corpus</strong> : une collection de documents. Cela équivalent à un ensemble de données de lignes / observations.
<li><strong>jeton/token</strong> : il s'agit d'un mot, d'une phrase ou de symboles. 
</ul>
<p>
Commençons par définir un corpus de quelques exemples de messages texte.
</p>

In [1]:
d0="Hey hey hey lets go get lunch today"
d1="Did you go home?"
d2="Go Hey!!! I need a favor"
corpus = [d0, d1, d2]
corpus

['Hey hey hey lets go get lunch today',
 'Did you go home?',
 'Go Hey!!! I need a favor']

## CountVectorizer
<p>
Tout d'abord, nous allons utiliser <strong>CountVectorizer()</strong> de sci-kit learn pour créer une matrice de nombres pour représenter nos messages. CountVectorizer() produit ce qu'on appelle un <strong>sac de mots (Bag Of Words)</strong>. Chaque message est divisé en tokens et le nombre de fois qu'un token apparaît dans un message est compté.
</p>
<p>
Pour commencer, nous allons importer <strong>CountVectorizer</strong> de sklearn et l'instancier en tant qu'objet, comme nous le ferons avec un classificateur de sklearn. En fait, l'utilisation est très similaire. Au lieu d'utiliser les méthodes <strong>fit()</strong> et <strong>predict()</strong>, nous utiliserons la méthode <strong>fit()</strong> puis la méthode <strong>transform()</strong>.
</p>

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
vect

CountVectorizer()

En utilisant la méthode fit(), CountVectorizer () va "apprendre" ce que les tokens qui sont utilisés dans nos messages.

In [3]:
vect.fit(corpus)

CountVectorizer()

En utilisant la méthode <strong>get_feature_names()</strong>, nous pouvons voir quelles caractéristiques (features) ont été créées à partir de nos messages. 

In [4]:
vect.get_feature_names_out()

array(['did', 'favor', 'get', 'go', 'hey', 'home', 'lets', 'lunch',
       'need', 'today', 'you'], dtype=object)

La propriété <strong>vocabulary_</strong> permet d'afficher le vocabulaire appris à partir de notre corpus

In [5]:
vect.vocabulary_

{'hey': 4,
 'lets': 6,
 'go': 3,
 'get': 2,
 'lunch': 7,
 'today': 9,
 'did': 0,
 'you': 10,
 'home': 5,
 'need': 8,
 'favor': 1}

<p>
Il y a quelques points à noter ici.
</p>
<ul>
<li>Tout est en minuscules
<li>Les mots de moins de deux lettres n'ont pas été inclus
<li>La ponctuation a été supprimée
<li>Il n'y a pas de doublons
</ul>
<p>
En changeant les arguments par défaut lorsque CountVectorizer est instancié, vous pouvez changer ce qui a été mentionné dans les deux premiers points si vous le souhaitez.
</p>
<p>
Ensuite, transformons notre objet CountVectorizer. Cela créera une matrice peuplée de nombres de tokens par message. Cette matrice est souvent appelé une term document matrix. 
</p>
<p>
Dans notre cas, nous allons nommer la sortie représentant cette matrice dtm (document term matrix). Nous pouvons aussi afficher des informations sur la matrice ainsi que la matrice elle-même.
</p>

In [6]:
 dtm = vect.transform(corpus)
print(dtm.toarray())
print(dtm)

[[0 0 1 1 3 0 1 1 0 1 0]
 [1 0 0 1 0 1 0 0 0 0 1]
 [0 1 0 1 1 0 0 0 1 0 0]]
  (0, 2)	1
  (0, 3)	1
  (0, 4)	3
  (0, 6)	1
  (0, 7)	1
  (0, 9)	1
  (1, 0)	1
  (1, 3)	1
  (1, 5)	1
  (1, 10)	1
  (2, 1)	1
  (2, 3)	1
  (2, 4)	1
  (2, 8)	1


<p>
Chacun de nos messages contient seulement 3 à 6 tokens uniques et nous avons 11 caractéristiques différentes créées à partir de tous les messages. Cela signifie que chaque ligne sera principalement remplie de zéros. 
</p>
<p>
Afin de gagner de l'espace / puissance de calcul, une matrice clairsemée (sparse matrix) est créée. Cela signifie que seul l'emplacement et la valeur des valeurs non nulles sont sauvegardés. Nous pouvons aussi la convertir sous forme d’un dataframe pandas pour une meilleure visualisation
</p>

In [7]:
import pandas as pd
pd.DataFrame(dtm.toarray(), columns=vect.get_feature_names_out())

did  favor  get  go  hey  home  lets  lunch  need  today  you
0    0      0    1   1    3     0     1      1     0      1    0
1    1      0    0   1    0     1     0      0     0      0    1
2    0      1    0   1    1     0     0      0     1      0    0

<p>
Par exemple, la troisième entrée dans notre matrice sparse est:
</p>
<strong><center>(0,4)    3</center></strong>

<p>
Ce qui correspond au 1er message et à la 5ème caractéristique, 'hey'. L'entrée est 3 car notre 1er message avait trois fois le mot 'hey'.
</p>
<p>
Nous sommes maintenant prêts à fournir une matrice de termes par documents à notre classificateur de Machine Learning.
</p>

### Remarque
Il y a une chose qu’il faut bien souligner. Supposons que nous avons reçu un autre message peu après avoir créé la matrice de terme par documents et que nous souhaitions l'ajouter. Nous allons le transformer en une matrice de terme par documents à l'aide de notre objet CountVectorizer () que nous avons adapté précédemment.

In [8]:
d4 = ['Hey lets go get a drink tonight']
new_dtm = vect.transform(d4)
pd.DataFrame(new_dtm.toarray(), columns=vect.get_feature_names_out())

did  favor  get  go  hey  home  lets  lunch  need  today  you
0    0      0    1   1    1     0     1      0     0      0    0

Maintenant, même s'il contient 6 tokens uniques (à l’exception de 'a'), il n'y a que 4 entrées dans notre dtm. Les tokens «drink» et «tonight» ne sont pas représentés. C'est parce que nos messages originaux utilisés pour CountVectorizer () n'avaient pas ces tokens. Nous pouvons ajouter notre nouveau message à notre collection originale, puis refit() et transform() pour nous assurer de ne pas perdre cette information. Au lieu de ça, nous allons utiliser la méthode fit_transform() combinant fit() et transform().

In [9]:
corpus.append(d4[0])
print(corpus)

dtm = vect.fit_transform(corpus)
pd.DataFrame(dtm.toarray(), columns=vect.get_feature_names_out())

['Hey hey hey lets go get lunch today', 'Did you go home?', 'Go Hey!!! I need a favor', 'Hey lets go get a drink tonight']


did  drink  favor  get  go  hey  home  lets  lunch  need  today  tonight  \
0    0      0      0    1   1    3     0     1      1     0      1        0   
1    1      0      0    0   1    0     1     0      0     0      0        0   
2    0      0      1    0   1    1     0     0      0     1      0        0   
3    0      1      0    1   1    1     0     1      0     0      0        1   

   you  
0    0  
1    1  
2    0  
3    0

## TfidfVectorizer
<p>
Une alternative à CountVectorizer() est la méthode TfidfVectorizer(). Cette méthode créée également une matrice de terme par documents à partir de nos messages. Cependant, au lieu de remplir le DTM avec des nombres de fois qu’un token apparaît dans un message (document), il calcule la valeur de la fréquence TF-IDF. 
</p>

### Rappel
<p>Pour claculer la valeur de IF-IDF, on utilise la formule suivante :</p>
<img src="images/tfidf.png">

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()
dtm = vect.fit_transform(corpus)
    
pd.DataFrame(dtm.toarray(), columns=vect.get_feature_names_out()) 


did     drink     favor       get        go       hey      home  \
0  0.000000  0.000000  0.000000  0.294188  0.194720  0.714511  0.000000   
1  0.552805  0.000000  0.000000  0.000000  0.288477  0.000000  0.552805   
2  0.000000  0.000000  0.610878  0.000000  0.318782  0.389916  0.000000   
3  0.000000  0.504889  0.000000  0.398060  0.263472  0.322264  0.000000   

       lets    lunch      need    today   tonight       you  
0  0.294188  0.37314  0.000000  0.37314  0.000000  0.000000  
1  0.000000  0.00000  0.000000  0.00000  0.000000  0.552805  
2  0.000000  0.00000  0.610878  0.00000  0.000000  0.000000  
3  0.398060  0.00000  0.000000  0.00000  0.504889  0.000000

## Calcul de la similarité Cosinus

<p>La similarité cosinus est fréquemment utilisée en tant que mesure de ressemblance entre deux documents. Il pourra s'agir de comparer les textes issus d'un corpus dans une optique de classification (regrouper tous les documents relatifs à une thématique particulière), ou de recherche d'information.
</p>

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(dtm[1:2], dtm)

array([[0.05617211, 1.        , 0.09196106, 0.0760055 ]])

## Exemple de synthèse

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd 

d0="he thinks that the sun is shining"
d1="The sky is blue"
d2="The sun is bright"
d3="The sun in the sky is bright"
d4="We can see the shining sun, the bright sun"

corpus =[d0, d1, d2, d3, d4]

#vect = CountVectorizer() # ==> TF
vect=TfidfVectorizer() # ==> TF-IDF
vect.fit(corpus)
dtm = vect.transform(corpus)
#print(dtm)
#print(dtm.toarray())
df = pd.DataFrame(dtm.toarray(), columns=vect.get_feature_names_out())
df
#cosine_similarity(dtm[0:1], dtm)

blue    bright       can        he        in        is       see  \
0  0.00000  0.000000  0.000000  0.470737  0.000000  0.265205  0.000000   
1  0.67491  0.000000  0.000000  0.000000  0.000000  0.380232  0.000000   
2  0.00000  0.585047  0.000000  0.000000  0.000000  0.492160  0.000000   
3  0.00000  0.350906  0.000000  0.000000  0.523965  0.295193  0.000000   
4  0.00000  0.267302  0.399131  0.000000  0.000000  0.000000  0.399131   

    shining       sky       sun      that       the    thinks        we  
0  0.379788  0.000000  0.265205  0.470737  0.224309  0.470737  0.000000  
1  0.000000  0.544513  0.000000  0.000000  0.321598  0.000000  0.000000  
2  0.000000  0.000000  0.492160  0.000000  0.416266  0.000000  0.000000  
3  0.000000  0.422732  0.295193  0.000000  0.499345  0.000000  0.000000  
4  0.322016  0.000000  0.449726  0.000000  0.380376  0.000000  0.399131

## Application
<p>
Etant donné un corpus constitué de plusieurs documents textuels, écrire un programme qui permet d'afficher les documents similaire à une requête donnée.
</p>
<p><strong>Proposition</strong></p>
<ul>
<li>Lire les documents et les stocker dans une liste : corpus
<li>Néttoyer le corpus : éliminer les stopwords, les ponctuations, symboles, ...
<li>Réduire les tokens en leurs racines
<li>Dégager le BOW
<li>Utiliser TF-IDF
<li>Uiliser la méthode de similarité Cosinus
</ul>

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np


d1="The sky is blue"
d2="The sun is bright"
d3="The sun in the sky is bright"
d4="We can see the shining sun, the bright sun"
files=[d1,d2,d3,d4]
"""
fichiers=['file1.txt','file2.txt','file3.txt','file4.txt']
files=[]
for file in fichiers:
    f=open(file,"r")
    l=f.read()
    f.close()
    files.append(l)


print(files)
"""
req = 'the weather is fine'#input("requette :")
files.append(req)
vect=TfidfVectorizer()
vect.fit(files)
dtm = vect.transform(files)
#pour ne pas calculer la similarité de la requête avec elle-même
similarities = cosine_similarity(dtm[4], dtm[0:4]) 
similarities, np.sort(similarities)

(array([[0.23036263, 0.28428975, 0.2489833 , 0.10646105]]),
 array([[0.10646105, 0.23036263, 0.2489833 , 0.28428975]]))

In [14]:
np.round(similarities,3)

array([[0.23 , 0.284, 0.249, 0.106]])

In [15]:
d={}
for i in range(len(files)-1):
    d[files[i]] = similarities[0,i]
d

{'The sky is blue': 0.2303626262240333,
 'The sun is bright': 0.28428974981323174,
 'The sun in the sky is bright': 0.24898329593578014,
 'We can see the shining sun, the bright sun': 0.10646104858688445}

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

fichiers=['files/file1.txt','files/file2.txt',
          'files/file3.txt','files/file4.txt']
corpus=[]
for file in fichiers:
    f=open(file,"r")
    data=f.read()
    f.close()
    corpus.append(data)

req = 'the weather is fine'#input("requette :")
corpus.append(req)
print(corpus)
vect=TfidfVectorizer()
vect.fit(corpus)
dtm = vect.transform(corpus)
#pour ne pas calculer la similarité de la requête avec elle-même
similarities = cosine_similarity(dtm[4], dtm[0:4]) 
similarities, np.sort(similarities[0])[::-1]

FileNotFoundError: [Errno 2] No such file or directory: 'files/file1.txt'

In [ ]:
import os
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

fichiers = []
for file in os.listdir("files/"):
    fichiers.append('files/'+file)


corpus=[]
for file in fichiers:
    f=open(file,"r")
    data=f.read()
    f.close()
    corpus.append(data)

req = 'the weather is fine'#input("requette :")
corpus.append(req)
print(corpus)
vect=TfidfVectorizer()
vect.fit(corpus)
dtm = vect.transform(corpus)
#pour ne pas calculer la similarité de la requête avec elle-même
similarities = cosine_similarity(dtm[4], dtm[0:4]) 
similarities, np.sort(similarities[0])[::-1]